### ISSUE TITLE
Getting an invariant violation error

### ISSUE THREAD

**Issue by shirleyc40** [sudhirkumarojhaa/react-native-slider-text#1]
I imported the module and pasted the example given, but gave me an invariant violation: 
![image](https://user-images.githubusercontent.com/36049621/86547695-cb04ff00-bf07-11ea-8f0b-f70fb5f7829f.png)

Reproduction steps:
install the prerequisites and package
import SliderText from "react-native-slider-text";
Paste the example from the README: 
`<SliderText
            maximumValue={10}
            stepValue={1}
            minimumValueLabel="Sedentary"
            maximumValueLabel="Very active"
            onValueChange={(id) => setActivity(id)}
            sliderValue={activity} />`

**Comment by sudhirkumarojhaa** [comment]
Not able to reproduce. Please check the latest updates. Thanks
